import{r as e}from"./assets/rolldown-runtime-DMWpINJ5.js";/* empty css                      */import{n as t,r as n,t as r}from"./assets/vendor-zG5q2fLY.js";(function(){let e=document.createElement(`link`).relList;if(e&&e.supports&&e.supports(`modulepreload`))return;for(let e of document.querySelectorAll(`link[rel="modulepreload"]`))n(e);new MutationObserver(e=>{for(let t of e)if(t.type===`childList`)for(let e of t.addedNodes)e.tagName===`LINK`&&e.rel===`modulepreload`&&n(e)}).observe(document,{childList:!0,subtree:!0});function t(e){let t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin===`use-credentials`?t.credentials=`include`:e.crossOrigin===`anonymous`?t.credentials=`omit`:t.credentials=`same-origin`,t}function n(e){if(e.ep)return;e.ep=!0;let n=t(e);fetch(e.href,n)}})();var i=`55713445-fbda8ed7255a2117e2c0a47fe`;async function a(e,t=1){console.log(`🟣 Запит до API:`,{query:e,page:t});try{let r=await n.get(`https://pixabay.com/api/`,{params:{key:i,q:e,image_type:`photo`,orientation:`horizontal`,safesearch:!0,page:t,per_page:15}});return console.log(`🟣 Відповідь API:`,r.data),r.data}catch(e){throw console.error(`Помилка API:`,e),e}}var o=null;function s(e,n=!0){let r=document.querySelector(`.gallery`),i=e.map(e=>`
    <li class="gallery-item">
      <a class="gallery-link" href="${e.largeImageURL}">
        <img
          class="gallery-image"
          src="${e.webformatURL}"
          alt="${e.tags}"
        />
      </a>
      <div class="image-info">
        <span>👍 ${e.likes}</span>
        <span>👁️ ${e.views}</span>
        <span>💬 ${e.comments}</span>
        <span>📥 ${e.downloads}</span>
      </div>
    </li>
  `).join(``);n?r.innerHTML=i:r.insertAdjacentHTML(`beforeend`,i),o&&o.destroy(),o=new t(`.gallery a`,{captionsData:`alt`,captionDelay:250})}function c(){let e=document.querySelector(`.gallery`);e&&(e.innerHTML=``)}function l(){let e=document.getElementById(`loader`);e&&e.classList.add(`show`)}function u(){let e=document.getElementById(`loader`);e&&e.classList.remove(`show`)}function d(){let e=document.getElementById(`load-more-btn`);e&&e.classList.add(`show`)}function f(){let e=document.getElementById(`load-more-btn`);e&&e.classList.remove(`show`)}var p=e(r(),1),m=document.getElementById(`search-form`),h=document.getElementById(`load-more-btn`),g=``,_=1,v=0,y=!1;function b(){let e=document.querySelector(`.gallery-item`);if(!e)return;let t=e.getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:`smooth`})}function x(){let e=Math.ceil(v/15);_>=e&&(f(),p.default.info({title:`Info`,message:`We're sorry, but you've reached the end of search results.`,position:`topRight`}))}async function S(e=!0){if(!y){y=!0,e?(_=1,f(),c()):f(),l();try{let t=await a(g,_);if(v=t.totalHits,t.hits.length===0&&_===1){p.default.error({title:`Error`,message:`Sorry, there are no images matching your search query. Please try again!`,position:`topRight`});return}s(t.hits,e);let n=_*15<v;t.hits.length>0&&n?d():_*15>=v&&x(),e||b()}catch{p.default.error({title:`Error`,message:`Something went wrong. Please try again later.`,position:`topRight`})}finally{u(),y=!1}}}m.addEventListener(`submit`,async e=>{e.preventDefault();let t=m.elements.searchQuery.value.trim();if(!t){p.default.warning({title:`Warning`,message:`Please enter a search term`,position:`topRight`});return}g=t,await S(!0),m.reset()}),h.addEventListener(`click`,async()=>{y||(_++,await S(!1))});
//# sourceMappingURL=index.js.map